version: '3'

services:
  server:
    build: server/
    # command: yarn start
    ports:
      - 3001:3001
  
  client:
    build: client/
    # command: yarn start
    # network_mode: host
    ports:
      - 3000:3000
    depends_on:
      - server
